site_name: Documentación BanBajío

nav:
  - Home: index.md
  - Móvil: mobile.md
  - Web: web.md

theme:
  name: readthedocs

plugins:
  #- pdf-export:
      #verbose: true
      #media_type: print
      #Ejecutar desde terminal export ENABLE_PDF_EXPORT=1 para encender
      #Ejecutar desde terminal unset ENABLE_PDF_EXPORT para apagar
      #enabled_if_env: ENABLE_PDF_EXPORT
      #combined: true
